"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env
# Configuración de IA Multi-Proveedor
AI_PROVIDER = config('AI_PROVIDER', default='demo')  # demo, groq, openai
GROQ_API_KEY = config('GROQ_API_KEY', default=None)
OPENAI_API_KEY = config('OPENAI_API_KEY', default='tu-api-key-aqui')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-3g3-z!3s6yt-ti@#xjkpkxpxfasem#sp051m(3c_j5@%p&8xm-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Configuración de hosts permitidos - Simplificada
ALLOWED_HOSTS = ['gastosweb.com', 'www.gastosweb.com', '167.114.2.88', 'localhost', '127.0.0.1']

# Orígenes de confianza para CSRF - Simplificada
CSRF_TRUSTED_ORIGINS = ['https://gastosweb.com', 'https://www.gastosweb.com', 'http://167.114.2.88']

# Configuración de proxy inverso (Nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Seguridad HTTPS en producción
if not DEBUG:
    SECURE_SSL_REDIRECT = False  # Nginx maneja la redirección (silencia W008)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False  # Permitir acceso desde JavaScript si necesario
    CSRF_COOKIE_SAMESITE = 'Lax'  # Más flexible que 'Strict'
    SESSION_COOKIE_SAMESITE = 'Lax'
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Desarrollo
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

# Silenciar warnings de seguridad conocidos y configurados correctamente
SILENCED_SYSTEM_CHECKS = [
    'security.W008',  # SECURE_SSL_REDIRECT - Nginx maneja la redirección
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gastos.apps.GastosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise para archivos estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gastos.middleware.OnboardingMiddleware',  # Onboarding para nuevos usuarios
    'gastos.middleware.FamiliaSecurityMiddleware',  # Seguridad y aislamiento de familias
]

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gastos.context_processors.gamificacion_context',  # Context processor de gamificación
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuración de base de datos para Railway (PostgreSQL) o SQLite local
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Producción: PostgreSQL en Railway
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Desarrollo: SQLite local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Directorio donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Directorio donde se recopilarán los archivos estáticos en producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración de WhiteNoise para archivos estáticos en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploads de usuarios - comprobantes, etc.)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Email settings (desarrollo - emails se muestran en consola)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'gastos@familia.com'

# Para producción, usar SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tu_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'tu_contraseña_o_app_password'
# DEFAULT_FROM_EMAIL = 'Gastos Familiares <gastos@familia.com>'

# ============================================================================
# CONFIGURACIÓN DE LOGGING
# ============================================================================

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module} {funcName}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # Handler para errores críticos en archivo separado
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # Handler para todos los logs de la aplicación
        'file_app': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'application.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # Handler para logs de Django (framework)
        'file_django': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
        # Handler para la consola (solo en desarrollo)
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_true'],
        },
        # Handler para enviar emails de errores críticos (solo en producción)
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Logger para la aplicación 'gastos'
        'gastos': {
            'handlers': ['file_app', 'file_error', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger para Django
        'django': {
            'handlers': ['file_django', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger para errores de Django
        'django.request': {
            'handlers': ['file_error', 'mail_admins', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Logger para la base de datos (útil para debugging)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',  # Cambiar a DEBUG para ver queries SQL
            'propagate': False,
        },
        # Logger raíz (catch-all)
        'root': {
            'handlers': ['file_app', 'console'],
            'level': 'INFO',
        },
    },
}

# Configuración adicional para producción
if not DEBUG:
    # En producción, reducir logs de consola
    LOGGING['handlers']['console']['level'] = 'ERROR'
    # Habilitar emails de errores a administradores
    ADMINS = [
        ('Admin', config('ADMIN_EMAIL', default='admin@gastos-familiares.com')),
    ]
    MANAGERS = ADMINS
