# Generated by Django 6.0.1 on 2026-01-14 02:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Plan')),
                ('tipo', models.CharField(choices=[('GRATIS', 'Plan Gratuito'), ('BASICO', 'Plan Básico'), ('PREMIUM', 'Plan Premium'), ('EMPRESARIAL', 'Plan Empresarial')], max_length=20, verbose_name='Tipo de Plan')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Mensual (COP)')),
                ('max_aportantes', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Aportantes')),
                ('max_gastos_mes', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Gastos por Mes')),
                ('max_categorias', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Categorías')),
                ('dias_prueba', models.IntegerField(default=0, verbose_name='Días de Prueba Gratis')),
                ('activo', models.BooleanField(default=True, verbose_name='Plan Activo')),
                ('caracteristicas', models.TextField(blank=True, help_text='Una característica por línea', verbose_name='Características del Plan')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Familia')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_inicio_suscripcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Inicio Suscripción')),
                ('fecha_fin_suscripcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin Suscripción')),
                ('suscripcion_activa', models.BooleanField(default=True, verbose_name='Suscripción Activa')),
                ('en_periodo_prueba', models.BooleanField(default=False, verbose_name='En Período de Prueba')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('miembros', models.ManyToManyField(related_name='familias', to=settings.AUTH_USER_MODEL, verbose_name='Miembros con acceso')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familias', to='gastos.plansuscripcion', verbose_name='Plan de Suscripción')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='gastos.familia', verbose_name='Familia')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingreso Mensual (COP)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportantes', to='gastos.familia', verbose_name='Familia')),
            ],
            options={
                'verbose_name': 'Aportante',
                'verbose_name_plural': 'Aportantes',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto (COP)')),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito/Débito'), ('PSE', 'PSE'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('BANCOLOMBIA', 'Transferencia Bancolombia'), ('EFECTY', 'Efecty'), ('BALOTO', 'Baloto')], max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pago')),
                ('referencia_pago', models.CharField(max_length=100, unique=True, verbose_name='Referencia de Pago')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gastos.familia', verbose_name='Familia')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.plansuscripcion', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='CodigoInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Invitación')),
                ('usado', models.BooleanField(default=False, verbose_name='Código Usado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usado por')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.plansuscripcion', verbose_name='Plan Asignado')),
            ],
            options={
                'verbose_name': 'Código de Invitación',
                'verbose_name_plural': 'Códigos de Invitación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Gasto')),
                ('tipo', models.CharField(choices=[('FIJO', 'Gasto Fijo'), ('VARIABLE', 'Gasto Variable')], help_text='Fijo: monto constante mensual. Variable: depende del consumo o uso.', max_length=10, verbose_name='Tipo de Gasto')),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto promedio o estimado mensual (opcional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Estimado (COP)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='gastos.categoriagasto', verbose_name='Categoría Principal')),
            ],
            options={
                'verbose_name': 'Subcategoría de Gasto',
                'verbose_name_plural': 'Subcategorías de Gastos',
                'ordering': ['categoria', 'tipo', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text="Descripción adicional (opcional, ej: 'Factura de enero')", max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto (COP)')),
                ('fecha', models.DateField(verbose_name='Fecha del Gasto')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('pagado_por', models.ForeignKey(help_text='Aportante que realizó el pago de este gasto', on_delete=django.db.models.deletion.PROTECT, related_name='gastos_pagados', to='gastos.aportante', verbose_name='Pagado por')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.subcategoriagasto', verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DistribucionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje (%)')),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Asignado (COP)')),
                ('aportante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones', to='gastos.aportante', verbose_name='Aportante')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='gastos.gasto', verbose_name='Gasto')),
            ],
            options={
                'verbose_name': 'Distribución de Gasto',
                'verbose_name_plural': 'Distribuciones de Gastos',
                'unique_together': {('gasto', 'aportante')},
            },
        ),
    ]
