# Generated by Django 6.0.1 on 2026-01-14 03:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Año')),
                ('total_gastos', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Gastos del Mes')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='gastos.familia', verbose_name='Familia')),
            ],
            options={
                'verbose_name': 'Conciliación Mensual',
                'verbose_name_plural': 'Conciliaciones Mensuales',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('familia', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Reintegro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto a Reintegrar')),
                ('pagado', models.BooleanField(default=False, verbose_name='Reintegro Pagado')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('comprobante', models.CharField(blank=True, max_length=200, verbose_name='Comprobante/Referencia')),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reintegros', to='gastos.conciliacionmensual', verbose_name='Conciliación')),
                ('de_aportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reintegros_debe_pagar', to='gastos.aportante', verbose_name='De (Quien Debe Pagar)')),
                ('para_aportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reintegros_debe_recibir', to='gastos.aportante', verbose_name='Para (Quien Debe Recibir)')),
            ],
            options={
                'verbose_name': 'Reintegro',
                'verbose_name_plural': 'Reintegros',
            },
        ),
        migrations.CreateModel(
            name='DetalleConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_esperado', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Esperado')),
                ('monto_debe_pagar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto que Debe Pagar')),
                ('monto_pago_real', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto que Pagó Realmente')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance (Pagó - Debe)')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado por el Aportante')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('aportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_conciliacion', to='gastos.aportante', verbose_name='Aportante')),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gastos.conciliacionmensual', verbose_name='Conciliación')),
            ],
            options={
                'verbose_name': 'Detalle de Conciliación',
                'verbose_name_plural': 'Detalles de Conciliación',
                'unique_together': {('conciliacion', 'aportante')},
            },
        ),
    ]
