# Generated by Django 6.0.1 on 2026-01-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_conciliacionmensual_reintegro_detalleconciliacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aportante',
            name='email',
            field=models.EmailField(blank=True, help_text='Email para notificaciones y confirmaciones', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='detalleconciliacion',
            name='codigo_confirmacion',
            field=models.CharField(blank=True, max_length=6, verbose_name='Código de Confirmación'),
        ),
        migrations.AddField(
            model_name='detalleconciliacion',
            name='email_enviado',
            field=models.BooleanField(default=False, verbose_name='Email Enviado'),
        ),
        migrations.AddField(
            model_name='detalleconciliacion',
            name='fecha_envio_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío de Email'),
        ),
    ]
