# Generated by Django 6.0.1 on 2026-01-14 23:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_aportante_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Meta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Objetivo')),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Ahorrado Actual')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_objetivo', models.DateField(verbose_name='Fecha Objetivo')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=15, verbose_name='Estado')),
                ('icono', models.CharField(default='piggy-bank', help_text='Nombre del ícono de Bootstrap Icons (ej: piggy-bank, house, car, etc.)', max_length=50, verbose_name='Icono')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_ahorro', to='gastos.familia', verbose_name='Familia')),
            ],
            options={
                'verbose_name': 'Meta de Ahorro',
                'verbose_name_plural': 'Metas de Ahorro',
                'ordering': ['-fecha_objetivo', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GASTO', 'Gasto Registrado'), ('PRESUPUESTO_ALERTA', 'Alerta de Presupuesto'), ('PRESUPUESTO_EXCEDIDO', 'Presupuesto Excedido'), ('META_LOGRADA', 'Meta Alcanzada'), ('META_PROGRESO', 'Progreso de Meta'), ('CONCILIACION', 'Conciliación Disponible'), ('REINTEGRO', 'Reintegro Pendiente'), ('SUSCRIPCION', 'Información de Suscripción'), ('SISTEMA', 'Notificación del Sistema')], max_length=30, verbose_name='Tipo de Notificación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('importante', models.BooleanField(default=False, verbose_name='Importante')),
                ('link', models.CharField(blank=True, help_text='URL relacionada con la notificación', max_length=500, verbose_name='Enlace')),
                ('icono', models.CharField(default='bell', help_text='Nombre del ícono de Bootstrap Icons', max_length=50, verbose_name='Icono')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('leida_en', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gastos.familia', verbose_name='Familia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Presupuestado')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('alertar_en', models.IntegerField(default=80, help_text='Porcentaje del presupuesto para enviar alerta (ej: 80 para alertar al 80%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Alertar al %')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='gastos.categoriagasto', verbose_name='Categoría')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='gastos.familia', verbose_name='Familia')),
            ],
            options={
                'verbose_name': 'Presupuesto de Categoría',
                'verbose_name_plural': 'Presupuestos de Categorías',
                'ordering': ['-anio', '-mes', 'categoria__nombre'],
                'unique_together': {('familia', 'categoria', 'mes', 'anio')},
            },
        ),
    ]
