# Generated by Django 6.0.1 on 2026-01-15 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_metaahorro_notificacion_presupuestocategoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='datos_qr',
            field=models.JSONField(blank=True, help_text='Información usada para generar el QR', null=True, verbose_name='Datos del QR'),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_transaccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Transacción'),
        ),
        migrations.AddField(
            model_name='pago',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICANDO', 'En Verificación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito/Débito'), ('PSE', 'PSE'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('BANCOLOMBIA', 'Transferencia Bancolombia'), ('EFECTY', 'Efecty'), ('BALOTO', 'Baloto'), ('QR_BANCOLOMBIA', 'QR Bancolombia'), ('QR_NEQUI', 'QR Nequi')], max_length=20, verbose_name='Método de Pago'),
        ),
    ]
