# Generated by Django 6.0.1 on 2026-01-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_pago_comprobante_pago_datos_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='max_archivos_adjuntos',
            field=models.IntegerField(default=0, help_text='Comprobantes, facturas, recibos (0 = sin adjuntos)', verbose_name='Archivos Adjuntos por Gasto'),
        ),
        migrations.AddField(
            model_name='plansuscripcion',
            name='permite_conciliacion_automatica',
            field=models.BooleanField(default=False, help_text='Cálculo automático de reintegros y distribución', verbose_name='Conciliación Automática'),
        ),
        migrations.AddField(
            model_name='plansuscripcion',
            name='permite_exportar_datos',
            field=models.BooleanField(default=False, help_text='Descargar datos en Excel, PDF, CSV', verbose_name='Exportar Datos'),
        ),
        migrations.AddField(
            model_name='plansuscripcion',
            name='permite_historial_completo',
            field=models.BooleanField(default=False, help_text='Acceso ilimitado al historial (Gratis solo 3 meses)', verbose_name='Historial Completo'),
        ),
        migrations.AddField(
            model_name='plansuscripcion',
            name='permite_notificaciones_email',
            field=models.BooleanField(default=False, help_text='Alertas de vencimientos, recordatorios, resúmenes mensuales', verbose_name='Notificaciones por Email'),
        ),
        migrations.AddField(
            model_name='plansuscripcion',
            name='permite_reportes_avanzados',
            field=models.BooleanField(default=False, help_text='Gráficos detallados, exportación PDF/Excel, análisis de tendencias', verbose_name='Reportes Avanzados'),
        ),
        migrations.AddField(
            model_name='plansuscripcion',
            name='soporte_prioritario',
            field=models.BooleanField(default=False, help_text='Respuesta en menos de 24 horas', verbose_name='Soporte Prioritario'),
        ),
    ]
