# Generated by Django 6.0.1 on 2026-01-17 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_plansuscripcion_max_archivos_adjuntos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('icono', models.CharField(default='🎯', max_length=50, verbose_name='Icono')),
                ('puntos_premio', models.IntegerField(default=150, verbose_name='Puntos de Premio')),
                ('meta_reduccion_categoria', models.CharField(blank=True, max_length=50, verbose_name='Categoría a Reducir')),
                ('meta_porcentaje', models.IntegerField(default=0, verbose_name='Porcentaje de Reducción')),
                ('meta_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Meta')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('PROXIMO', 'Próximo')], default='PROXIMO', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Desafío Mensual',
                'verbose_name_plural': 'Desafíos Mensuales',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('ACTIVIDAD', 'Actividad Diaria'), ('AHORRO', 'Ahorro'), ('DISCIPLINA', 'Disciplina Financiera'), ('SOCIAL', 'Social'), ('ESPECIAL', 'Especial')], max_length=20, verbose_name='Tipo')),
                ('puntos_recompensa', models.IntegerField(default=10, verbose_name='Puntos de Recompensa')),
                ('icono', models.CharField(default='🏆', max_length=50, verbose_name='Icono')),
                ('requisito_numero', models.IntegerField(default=1, help_text='Ej: 7 días, 3 meses, $50000', verbose_name='Requisito Numérico')),
                ('requisito_tipo', models.CharField(help_text='dias_consecutivos, meses_cumplidos, monto_ahorrado', max_length=50, verbose_name='Tipo de Requisito')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_secreto', models.BooleanField(default=False, verbose_name='Es Secreto')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['tipo', 'puntos_recompensa'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(default=0, verbose_name='Puntos Totales')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('experiencia_nivel_actual', models.IntegerField(default=0, verbose_name='Experiencia en Nivel Actual')),
                ('dias_consecutivos', models.IntegerField(default=0, verbose_name='Días Consecutivos')),
                ('ultima_actividad', models.DateField(auto_now=True, verbose_name='Última Actividad')),
                ('fecha_registro_app', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('total_gastos_registrados', models.IntegerField(default=0, verbose_name='Total Gastos Registrados')),
                ('total_ahorrado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ahorrado')),
                ('racha_actual', models.IntegerField(default=0, verbose_name='Racha Actual')),
                ('mejor_racha', models.IntegerField(default=0, verbose_name='Mejor Racha')),
                ('visitas_dashboard', models.IntegerField(default=0, verbose_name='Visitas al Dashboard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_gamificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='NotificacionLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGRO', 'Logro Desbloqueado'), ('NIVEL', 'Subida de Nivel'), ('DESAFIO', 'Desafío Completado'), ('RACHA', 'Racha Alcanzada')], max_length=20, verbose_name='Tipo')),
                ('mensaje', models.CharField(max_length=200, verbose_name='Mensaje')),
                ('visto', models.BooleanField(default=False, verbose_name='Visto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_logro', to='gastos.perfilusuario')),
            ],
            options={
                'verbose_name': 'Notificación de Logro',
                'verbose_name_plural': 'Notificaciones de Logros',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(verbose_name='Puntos')),
                ('razon', models.CharField(max_length=200, verbose_name='Razón')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puntos', to='gastos.perfilusuario')),
            ],
            options={
                'verbose_name': 'Historial de Puntos',
                'verbose_name_plural': 'Historial de Puntos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('progreso_porcentaje', models.IntegerField(default=0, verbose_name='Progreso (%)')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_completado', models.DateField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.desafiomensual')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.perfilusuario')),
            ],
            options={
                'verbose_name': 'Participación en Desafío',
                'verbose_name_plural': 'Participaciones en Desafíos',
                'unique_together': {('perfil', 'desafio')},
            },
        ),
        migrations.CreateModel(
            name='LogroDesbloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Desbloqueo')),
                ('visto', models.BooleanField(default=False, verbose_name='Visto')),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.logro')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='gastos.perfilusuario')),
            ],
            options={
                'verbose_name': 'Logro Desbloqueado',
                'verbose_name_plural': 'Logros Desbloqueados',
                'ordering': ['-fecha_desbloqueo'],
                'unique_together': {('perfil', 'logro')},
            },
        ),
    ]
