# Generated by Django 6.0.1 on 2026-01-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_desafiomensual_logro_perfilusuario_notificacionlogro_and_more'),
    ]

    operations = [
    ]
