# Generated by Django 6.0.1 on 2026-01-17 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_add_gamificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AHORRO', 'Oportunidades de Ahorro'), ('PATRON', 'Patrones de Gasto'), ('PREDICCION', 'Predicción de Gastos'), ('RECOMENDACION', 'Recomendación Personalizada'), ('ALERTA', 'Alerta Financiera')], max_length=20, verbose_name='Tipo de Análisis')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido del Análisis')),
                ('datos_json', models.JSONField(blank=True, null=True, verbose_name='Datos Adicionales')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Generado en')),
                ('visto', models.BooleanField(default=False, verbose_name='Visto por Usuario')),
                ('relevancia', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Relevancia (1-10)')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.familia', verbose_name='Familia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis IA',
                'verbose_name_plural': 'Análisis IA',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ConversacionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Conversación')),
                ('iniciada_en', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada en')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activa', models.BooleanField(default=True, verbose_name='Conversación Activa')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.familia', verbose_name='Familia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_chatbot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación Chatbot',
                'verbose_name_plural': 'Conversaciones Chatbot',
                'ordering': ['-actualizada_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=10, verbose_name='Rol')),
                ('contenido', models.TextField(verbose_name='Contenido del Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('tokens_usados', models.IntegerField(default=0, verbose_name='Tokens Usados')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='gastos.conversacionchatbot', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje Chatbot',
                'verbose_name_plural': 'Mensajes Chatbot',
                'ordering': ['fecha'],
            },
        ),
    ]
