# Generated by Django 6.0.1 on 2026-01-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_analisisia_conversacionchatbot_mensajechatbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCuentaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('BANCOLOMBIA', 'Bancolombia'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('OTRO', 'Otro')], max_length=20, unique=True, verbose_name='Método de Pago')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre_banco', models.CharField(max_length=100, verbose_name='Nombre del Banco/Entidad')),
                ('tipo_cuenta', models.CharField(choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente'), ('NEQUI', 'Cuenta Nequi'), ('DAVIPLATA', 'Cuenta Daviplata')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(help_text='Para Bancolombia: número de cuenta. Para Nequi: número de celular', max_length=50, verbose_name='Número de Cuenta/Celular')),
                ('titular', models.CharField(max_length=200, verbose_name='Titular de la Cuenta')),
                ('nit', models.CharField(blank=True, help_text='Opcional, solo para empresas', max_length=50, verbose_name='NIT')),
                ('color', models.CharField(default='#3498db', help_text='Código hexadecimal, ej: #FFDD00', max_length=7, verbose_name='Color del Botón')),
                ('icono', models.CharField(default='💳', max_length=10, verbose_name='Emoji/Icono')),
                ('instrucciones', models.TextField(blank=True, help_text='Una instrucción por línea', verbose_name='Instrucciones para el Usuario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Cuenta de Pago',
                'verbose_name_plural': 'Configuraciones de Cuentas de Pago',
                'ordering': ['metodo'],
            },
        ),
    ]
