# Generated by Django 6.0.1 on 2026-01-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0010_configuracioncuentapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='expira_en',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del QR (24 horas por defecto)', null=True, verbose_name='Expira En'),
        ),
        migrations.AddField(
            model_name='pago',
            name='firma_qr',
            field=models.CharField(blank=True, help_text='Firma digital para validar integridad', max_length=64, verbose_name='Firma del QR'),
        ),
        migrations.AddField(
            model_name='pago',
            name='intentos_subida',
            field=models.IntegerField(default=0, help_text='Número de veces que se intentó subir comprobante', verbose_name='Intentos de Subida'),
        ),
        migrations.AddField(
            model_name='pago',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, help_text='IP desde donde se generó el pago', null=True, verbose_name='IP de Origen'),
        ),
        migrations.AddField(
            model_name='pago',
            name='max_intentos',
            field=models.IntegerField(default=5, help_text='Máximo número de intentos permitidos', verbose_name='Máximo de Intentos'),
        ),
    ]
