# Generated by Django 5.0 on 2026-01-22 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0011_pago_expira_en_pago_firma_qr_pago_intentos_subida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único para unirse a la familia', max_length=12, unique=True, verbose_name='Código de Invitación')),
                ('email_invitado', models.EmailField(blank=True, help_text='Email opcional del usuario invitado', max_length=254, null=True, verbose_name='Email del Invitado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha hasta la cual el código es válido', verbose_name='Fecha de Expiración')),
                ('fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso')),
                ('mensaje_invitacion', models.TextField(blank=True, help_text='Mensaje personalizado para el invitado', verbose_name='Mensaje de Invitación')),
                ('usos_maximos', models.IntegerField(default=1, help_text='Número máximo de veces que puede usarse el código (0 = ilimitado)', verbose_name='Usos Máximos')),
                ('usos_actuales', models.IntegerField(default=0, verbose_name='Usos Actuales')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='gastos.familia', verbose_name='Familia')),
                ('usado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_usadas', to=settings.AUTH_USER_MODEL, verbose_name='Usado por')),
            ],
            options={
                'verbose_name': 'Invitación a Familia',
                'verbose_name_plural': 'Invitaciones a Familias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
