# Generated by Django 6.0.1 on 2026-02-01 16:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0014_preferenciasusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.CharField(choices=[('COMPARTIDO', 'Gasto Compartido'), ('PERSONAL', 'Gasto Personal')], default='COMPARTIDO', help_text='Compartido: se distribuye entre aportantes. Personal: solo afecta al pagador', max_length=20, verbose_name='Tipo de Gasto'),
        ),
        migrations.CreateModel(
            name='IngresoAportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('SALARIO', 'Salario'), ('BONO', 'Bono/Prima'), ('COMISION', 'Comisión'), ('FREELANCE', 'Trabajo Freelance'), ('INVERSION', 'Rendimiento Inversión'), ('ARRIENDO', 'Arriendo'), ('PENSION', 'Pensión'), ('SUBSIDIO', 'Subsidio'), ('OTRO', 'Otro Ingreso')], default='SALARIO', max_length=20, verbose_name='Tipo de Ingreso')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción adicional (opcional)', max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto (COP)')),
                ('fecha', models.DateField(verbose_name='Fecha del Ingreso')),
                ('recurrente', models.BooleanField(default=False, help_text='Marcar si es un ingreso mensual recurrente', verbose_name='Recurrente')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('aportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='gastos.aportante', verbose_name='Aportante')),
            ],
            options={
                'verbose_name': 'Ingreso de Aportante',
                'verbose_name_plural': 'Ingresos de Aportantes',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
