# Generated by Django 6.0.1 on 2026-02-01 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0015_gasto_tipo_gasto_ingresoaportante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('EXPORT', 'Exportar'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('LOGIN_FAILED', 'Intento de Login Fallido'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PAYMENT', 'Pago/Suscripción')], max_length=20, verbose_name='Acción')),
                ('modelo', models.CharField(help_text='Nombre del modelo afectado (Gasto, Aportante, etc.)', max_length=100, verbose_name='Modelo/Entidad')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado antes del cambio (JSON)', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado después del cambio (JSON)', null=True, verbose_name='Datos Nuevos')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la acción', verbose_name='Descripción')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='gastos.familia', verbose_name='Familia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='gastos_audi_usuario_fa4e51_idx'), models.Index(fields=['accion', '-timestamp'], name='gastos_audi_accion_3ec41b_idx'), models.Index(fields=['familia', '-timestamp'], name='gastos_audi_familia_fa885d_idx')],
            },
        ),
    ]
