# Generated by Django 6.0.1 on 2026-02-01 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0016_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Si tiene valor, el registro está eliminado (soft delete)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
    ]
