# Generated by Django 6.0.1 on 2026-02-13 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0017_gasto_deleted_at_gasto_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacionmensual',
            name='destino_saldo',
            field=models.CharField(blank=True, choices=[('AHORRO', 'Ahorro Familiar'), ('EMERGENCIA', 'Fondo de Emergencia'), ('SIGUIENTE_MES', 'Reserva para Próximo Mes'), ('DISTRIBUIR_PROPORCION', 'Distribuir Proporcionalmente'), ('DISTRIBUIR_IGUAL', 'Distribuir en Partes Iguales')], help_text='¿Qué hacer con el saldo positivo?', max_length=30, null=True, verbose_name='Destino del Saldo Sobrante'),
        ),
        migrations.AddField(
            model_name='conciliacionmensual',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo disponible transferido del mes anterior', max_digits=12, verbose_name='Saldo del Mes Anterior'),
        ),
        migrations.AddField(
            model_name='conciliacionmensual',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingresos + Saldo Anterior - Gastos', max_digits=12, verbose_name='Saldo Disponible'),
        ),
        migrations.AddField(
            model_name='conciliacionmensual',
            name='saldo_transferido_siguiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Transferido al Siguiente Mes'),
        ),
        migrations.AddField(
            model_name='conciliacionmensual',
            name='total_ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de Ingresos del Mes'),
        ),
    ]
